/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/w77HnzqZgkm
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */

/** Add fonts into your Next.js project:

import { Inter } from 'next/font/google'

inter({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client";

import { useState } from "react";
import { Card, CardContent, CardFooter } from "~/components/ui/card";
import { Avatar, AvatarImage, AvatarFallback } from "~/components/ui/avatar";
import { Button } from "~/components/ui/button";
import Image from "next/image";
import { allPosts, increaseLikes } from "~/server/actions";
import { HeartFilledIcon, HeartIcon } from "@radix-ui/react-icons";
import { useRouter } from "next/navigation";

export default function PostCard({ post }: { post: allPosts }) {
  const router = useRouter();
  const [isLiked, setIsLiked] = useState<boolean>(false);
  const [likes, setLikes] = useState<number>(post.posts.likes);
  const handleLike = async () => {
    setIsLiked((isLiked) => !isLiked);
    if (isLiked) {
      setLikes((likes) => likes - 1);
    } else {
      setLikes((likes) => likes + 1);
    }
    const postID = post.posts.id;
    router.refresh();
  };

  return (
    <Card className="group max-w-md">
      <CardContent className="p-0">
        <Image
          src={post.posts.url}
          alt="Post image"
          width={800}
          height={600}
          className="aspect-video w-full object-cover transition-opacity duration-300 group-hover:opacity-90"
        />
      </CardContent>
      <CardFooter className="p-4">
        <div className="flex items-center justify-between">
          <div className="flex items-center gap-3">
            <Avatar>
              <AvatarImage src={post.userImg} />
              <AvatarFallback>CN</AvatarFallback>
            </Avatar>
            <div className="grid gap-1">
              <div className="font-medium">{post.userName}</div>
              <div className="text-sm text-muted-foreground">
                @{post.userName}
              </div>
            </div>
          </div>
          <div className="flex flex-col items-center px-2">
            <Button
              variant="ghost"
              size="icon"
              onClick={handleLike}
              className={`text-muted-foreground ${isLiked ? "text-red-500" : ""}`}
            >
              {!isLiked ? (
                <HeartIcon className="h-5 w-5" />
              ) : (
                <HeartFilledIcon className="h-5 w-5" />
              )}
              <span className="sr-only">Like</span>
            </Button>
            <span className="text-sm font-medium">{likes}</span>
          </div>
        </div>
        <p className="mt-4 text-sm text-muted-foreground">
          {post.posts.caption}
        </p>
      </CardFooter>
    </Card>
  );
}
