import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";
import { Navbarv0 } from "~/components/component/navbarv0";
import { db } from "~/server/db";
import { users } from "~/server/db/schema";

export const metadata: Metadata = {
  title: "Social-Media-App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  // const query = await db.select({ id: users.id }).from(users).toSQL();
  // console.log(query);
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <Navbarv0 />
        {children}
      </body>
    </html>
  );
}
